version: "3.3"
services:
  bt_mysql:
    image: mysql:5.7
    restart: always
    command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4

    environment:
      MYSQL_DATABASE: "prod-db"
      # So you don't have to use root, but you can if you like
      MYSQL_USER: "ahmetlevent"
      # You can use whatever password you like
      MYSQL_PASSWORD: "123321"
      # Password for root access
      MYSQL_ROOT_PASSWORD: "UQ@sGxOBYit{WJp/c2Ju"
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - "3306:3306"
